data = load_from_file();
data = pre_process(data);
[train, test] = data_division(data, 9);
final = [];
[X, y] = pca_data_load(train, 1);
[res, Eig_vecs, average] = pca_cont(X, 20);
rank = prd(X', Eig_vecs, 20);
disp(['The PRD of the subspace is ' num2str(rank) '.']);
final = [final res];
models = train_svm_new(X, y');
percentage = pca_test(models, test, Eig_vecs, average, 1);
